// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrcamentosAPI.Data;

#nullable disable

namespace OrcamentosAPI.Migrations
{
    [DbContext(typeof(LivroContext))]
    [Migration("20220821172227_incluindoTabelaOrcamento2")]
    partial class incluindoTabelaOrcamento2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OrcamentosAPI.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QtdPaginas")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("OrcamentosAPI.Models.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("ComissaoVendedor")
                        .HasColumnType("double");

                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.Property<double>("QtdLivros")
                        .HasColumnType("double");

                    b.Property<double>("ValorPorLivro")
                        .HasColumnType("double");

                    b.Property<double>("ValorPorPagina")
                        .HasColumnType("double");

                    b.Property<double>("ValorTotalLivros")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("Orcamentos");
                });

            modelBuilder.Entity("OrcamentosAPI.Models.Orcamento", b =>
                {
                    b.HasOne("OrcamentosAPI.Models.Livro", "Livro")
                        .WithMany("Orcamentos")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("OrcamentosAPI.Models.Livro", b =>
                {
                    b.Navigation("Orcamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
